### ISSUE TITLE
camera calibration

### ISSUE THREAD

**Issue by hadi1376tm** [TemugeB/bodypose3d#1]
Hi, love your project, may i ask what calibration toolbox did you use? is it possible to use more than two cameras with your project?

**Comment by TemugeB** [comment]
Hi,

I don't use any calibration toolbox but I wrote a simple guide here for calibration: [link](https://temugeb.github.io/opencv/python/2021/02/02/stereo-camera-calibration-and-triangulation.html). Make sure you print out a bigger calibration pattern than the one I used and stick it to something as flat as you can find. Otherwise small errors in the calibration pattern lead to large 3D triangulation results. 

If you want to use some toolbox for calibration, you can also do that. Just save camera parameters in the same format as my examples in "camera_parameters" folder or rewrite the code to read your own camera parameters. In some cases, the camera manufacturer will post the intrinsic camera matrix in their manual. You can try to look that up. 

You can use more than 2 cameras but the DLT function in utils.py need to be updated. Check here for how the math for DLT works here: [link](https://temugeb.github.io/computer_vision/2021/02/06/direct-linear-transorms.html).

Essentially you need to add additional entries to the **A** matrix here:
![image](https://user-images.githubusercontent.com/36071915/138629283-2b1d0810-ead6-4582-b12c-a05b3f4f5c09.png)

This is in line 14 of utils.py. On top of this, you need to modify the bodypose3d.py (line 28) to add additional body pose estimators. 

Finally, most of this camera related math is based on the pinhole camera model. Check here if you're not familiar with the concepts: [link](https://docs.opencv.org/4.5.3/d9/d0c/group__calib3d.html)

**Comment by hadi1376tm** [comment]
> 
> 
> Hi,
> 
> I don't use any calibration toolbox but I wrote a simple guide here for calibration: [link](https://temugeb.github.io/opencv/python/2021/02/02/stereo-camera-calibration-and-triangulation.html). Make sure you print out a bigger calibration pattern than the one I used and stick it to something as flat as you can find. Otherwise small errors in the calibration pattern lead to large 3D triangulation results.
> 
> If you want to use some toolbox for calibration, you can also do that. Just save camera parameters in the same format as my examples in "camera_parameters" folder or rewrite the code to read your own camera parameters. In some cases, the camera manufacturer will post the intrinsic camera matrix in their manual. You can try to look that up.
> 
> You can use more than 2 cameras but the DLT function in utils.py need to be updated. Check here for how the math for DLT works here: [link](https://temugeb.github.io/computer_vision/2021/02/06/direct-linear-transorms.html).
> 
> Essentially you need to add additional entries to the **A** matrix here: ![image](https://user-images.githubusercontent.com/36071915/138629283-2b1d0810-ead6-4582-b12c-a05b3f4f5c09.png)
> 
> This is in line 14 of utils.py. On top of this, you need to modify the bodypose3d.py (line 28) to add additional body pose estimators.
> 
> Finally, most of this camera related math is based on the pinhole camera model. Check here if you're not familiar with the concepts: [link](https://docs.opencv.org/4.5.3/d9/d0c/group__calib3d.html)

thank you very much.
