### ISSUE TITLE
How to implement with our own camera parameters?

### ISSUE THREAD

**Issue by rajeshaouti** [TemugeB/bodypose3d#2]
Hi,
I am working on human pose estimation and 3d reconstruction. I came across your repository and it helped me a lot. I would like to thank you for the detailed explanation.
I had one doubt regarding the implementation of the same with my camera parameters. The co1 and co2 matrices are found by the calibrate function applied in individual cameras, but how was rot_trans_co and rot_trans_c1 computed.
In one the blogs where you talk about triangulation, there the rot_trans_co was just an identity matrix and rot_trans_c1 the rotational matrix computed by the stereo calibration, I was not able to understand how to implement the same in the body pose estimation as they had two rotational and translation matrices for each camera. How do you get that as camera calibration only gives the intrinsic parameters and the rotational and translation vectors for each frame. 
Could you help me with the same.
Really Appreciate your work.

**Comment by TemugeB** [comment]
Thanks for checking out my repository. I assume you have no problems getting the intrinsic camera parameters.

Let's first go over what the rotation and translation are. We first imagine there is an origin point (world origin) from which everything is being measured. Also there are two cameras, both of which have their own coordinate systems. See the image below. There is a point, **x**_w measured from the world coordinates. We need to know the coordinates of this point in the camera_0 and camera_1 coordinate systems. These points are **x**_0 and **x**_1. If these points are known in each camera coordinate system, then their corresponding camera pixel coordinates can be found by using the camera intrinsic parameters.
![image](https://user-images.githubusercontent.com/36071915/151298428-34628ddc-1695-4721-90b2-9cdd27b271d9.png)

If we know the rotation and translation information that takes world origin to camera 0 or 1 coordinates systems, then these points can be calculated easily:
<img src="https://latex.codecogs.com/svg.image?\bold{x}_0&space;=&space;R_{w0}&space;\bold{x}_w&space;&plus;&space;T_{w0}" title="\bold{x}_0 = R_{w0} \bold{x}_w + T_{w0}" />

<img src="https://latex.codecogs.com/svg.image?\bold{x}_1&space;=&space;R_{w1}&space;\bold{x}_w&space;&plus;&space;T_{w1}" title="\bold{x}_1 = R_{w1} \bold{x}_w + T_{w1}" />

Here, R_w0 and T_w0 are rotation and translations that take world coordinates to camera_0 coordinates. So all we need to determine are R_w0, T_w0, R_w1 and T_w1. The trick that I mentioned in my blog post is that you can choose camera_0 as your world origin. In that case, R_w0 is identity matrix and T_w0 is a zeros vector. So then, only R_w1 an T_w1 are necessary to be computed. Since we chose camera_0 as origin, we can write these as R_01 and T_01.

To get the extrinsic parameters (rotation and translation), you need to use cv.stereoCalibrate() function [link](https://docs.opencv.org/4.x/d9/d0c/group__calib3d.html#ga91018d80e2a93ade37539f01e6f07de5). This function returns rotation and translation from camera_0 to camera_1: R_01 and T_01. 

So all you need to do is then put identity matrix and zeros vector in rot_trans_c0, and put the output of cv.stereoCalibrate() in rot_trans_c1.

Hope this answers your question. Do you need to specifically define a different world space origin? In that case, cv.stereoCalibrate() only returns R_01 and T_01 and you need a few more steps to calculate R_w0, T_w0, R_w1 and T_w1. Let me know if this is the case. 

If you're not familiar with the pinhole camera model, I suggest you look it up. OpenCV has a good intro here and the concepts are easy to understand. [Pinhole camera model](https://docs.opencv.org/4.x/d9/d0c/group__calib3d.html#:~:text=Detailed%20Description)

**Comment by rajeshaouti** [comment]
Thank you for clarifying, it helped me.I wanted to know why your rot_trans_co was not an identity and a zero vector for the rotational matrix and translation vector.
I presume you used a different world coordinate compared to the camera 1 coordinates.If that is the case how should i approach the problem.

**Comment by TemugeB** [comment]
Yes, the rotation matrix and translation vector in rot_trans_c0 is using a different world origin. This is relatively easy to set using a calibration pattern. When you use cv.calibrateCamera, this function also returns rotation and translation to go from the calibration pattern coordinate system to camera coordinate system. The calibration pattern has a coordinate system defined like this, where z points into the pattern:
![image](https://user-images.githubusercontent.com/36071915/151496836-13d514a7-5ebc-44e5-b0a2-4bd6221a0f51.png)

So when you hold the calibration pattern in front of your primary camera, this coordinate system will be generated in your working space and you can use it as your world space origin. If you have to specify a world space origin, then hold the calibration pattern at that spot and make sure the camera can see it clearly. If your calibration pattern is too small or too angled towards the camera, you will get poor calibration results so I suggest a big calibration pattern. 

Once you've taken a picture of the calibration pattern, use cv.calibrateCamera to obtain R_p0 and T_p0, where p0 means calibration **p**attern to camera **0**. So these will be your R_w0 and T_w0 from my previous reply.

To get R_w1 and T_w1:
<img src="https://latex.codecogs.com/svg.image?\bold{x}_1&space;=&space;R_{01}&space;\bold{x}_0&space;&plus;&space;T_{01}" title="\bold{x}_1 = R_{01} \bold{x}_0 + T_{01}" />
<img src="https://latex.codecogs.com/svg.image?\bold{x}_1&space;=&space;R_{01}&space;(R_{w0}\bold{x}_w&space;&plus;&space;T_{w0})&space;&space;&plus;&space;T_{01}" title="\bold{x}_1 = R_{01} (R_{w0}\bold{x}_w + T_{w0}) + T_{01}" />
<img src="https://latex.codecogs.com/svg.image?\bold{x}_1&space;=&space;R_{01}R_{w0}\bold{x}_w&space;&plus;&space;R_{01}T_{w0}&space;&space;&plus;&space;T_{01}" title="\bold{x}_1 = R_{01}R_{w0}\bold{x}_w + R_{01}T_{w0} + T_{01}" />
So:
<img src="https://latex.codecogs.com/svg.image?R_{w1}&space;=&space;R_{01}R_{w0}" title="R_{w1} = R_{01}R_{w0}" />
<img src="https://latex.codecogs.com/svg.image?T_{w1}&space;=&space;R_{01}T_{w0}&space;&plus;&space;T_{01}" title="T_{w1} = R_{01}T_{w0} + T_{01}" />

Hopefully I got the math correct. R_01 and T_01 are what you obtained from cv.stereoCalibrate, and converts camera0 points to camera1 coordinates system points. So once you've calculated R_w0, T_w0, R_w1 and T_w1, then put these in the rot_trans_c0 and c1 files. One thing to mention is that the rvec output from cv.calibrateCamera is in Rodrigues notation, so you need to convert it to matrix notation using cv.Rodrigues(rvec).

Let me know if you have any problems.

**Comment by TemugeB** [comment]
Here is another figure. This calibration pattern creates this coordinate system in my working space, with z pointing into the calibration patter. 
![image](https://user-images.githubusercontent.com/36071915/151500115-2cd321ad-feb1-4ca3-8a06-264bd5290381.png)

**Comment by rajeshaouti** [comment]
Thank you for the help. Really appreciate it.

**Comment by IssaIssa1** [comment]
Thank you for the explanation. One question, how would changing the world coordinates (which later obtains different rotation and translation from identify matrix and zeros vector) would affect the DLT or its precision?

**Comment by TemugeB** [comment]
Once you have the 3D points in any coordinate system, changing to a different coordinate system is simply applying rotation and translation. So it has no effect on the triangulation or its precision. However, the translation vector contain scale information. So there is something to be careful about. The 3D points obtained from using the calibration pattern has scale of 1 calibration box size. Depending on the printer and paper size, 1 calibration pattern box might be 1 cm to 5 cm. So this scaling should be corrected before applying rotation and translation to any other coordinate system.
