### ISSUE TITLE
Question regarding view calculation

### ISSUE THREAD

**Issue by Nophlock** [TemugeB/bodypose3d#5]
Hey, I just stumbled upon your repository and while looking through your code I had two general question about it. 

1. Is in regard to the calibration step of the camera. Since mediapipe already offers 3D-keypoints (but obviously lacks in precision) I wonder if it is possible to create the calibration based on the detected human. I'm currently thinking of extracting the rotation data of the 3D-Pose and also the translation of it and use this as the calculation of the camera position instead of a determent it through the checkerboard. Do you think this is possible, or would that be too imprecise to actually work? 
2. Did I understand your code correctly that it is only possible to detect the 3D-Position of key points that are visible in both cameras? So if one camera is detecting a key point that isn't visible on the other camera, it couldn't be used for the correct 3D-Position calculation? 

Sorry if my questions sounds stupid, but I'm a total noob on this topic and just getting started to understand this 3D-Projection thing. 

Thanks for the example code and any further help.

**Comment by TemugeB** [comment]
Hi. Thanks for checking out my repository. 

1. Mediapipe does output relative Z coordinate. If you want absolute coordinates with respect to the world origin, then you need two cameras. It is up to you to decide if the relative Z coordinate is enough for your application. 
About calibration, the detected keypoints themselves are not very reliable because keypoints are defined to be inside the human body part, from which the network estimates the surface keypoint. This is an important nuance to keep in mind because it likely results in the most error in 3D triangulation. On the other hand, even the smallest error in point correspondences in the two cameras result in big error in calibration matrices. Even if you use a calibration pattern, if the pattern is warped or some points are hard to see, the resulting calibration matrix will be very poor. So it is very important to use calibration pattern and keep it as flat as possible and well lit. The point is, even if what you suggest is possible, I don't think it will result in a useful camera calibration. 
Actually I get a bunch of camera calibration questions so I really should write a program to do this automatically.   
2. Yes if the camera does not see the keypoint, then the 3D point will be assigned values: [-1, -1, -1]. So you need to check for these and remove or handle them.

Hope these help. You learn a lot from manually going through camera calibration so I recommend doing it yourself.

**Comment by Nophlock** [comment]
Hi, 

thanks for the fast reply, helps me a lot.
